language: php

php:
  - 7.0
  - 7.1.0a1

matrix:
  allow_failures:
    - php: 7.1.0a1

before_script:
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls --coverage_clover=build/logs/clover.xml
